# Major S&P 500 / high-profile companies: ticker -> (full name, common aliases)
COMPANIES = {
    "AAPL": ("Apple", ["Apple Inc", "Apple Computer"]),
    "MSFT": ("Microsoft", ["Microsoft Corp"]),
    "GOOGL": ("Google", ["Alphabet", "Google Inc"]),
    "GOOG": ("Google", ["Alphabet"]),
    "AMZN": ("Amazon", ["Amazon.com", "Amazon Inc"]),
    "NVDA": ("Nvidia", ["NVIDIA Corp", "Nvidia Corporation"]),
    "META": ("Meta", ["Meta Platforms", "Facebook"]),
    "TSLA": ("Tesla", ["Tesla Inc", "Tesla Motors"]),
    "BRK": ("Berkshire Hathaway", ["Berkshire"]),
    "JPM": ("JPMorgan", ["JPMorgan Chase", "JP Morgan"]),
    "V": ("Visa", ["Visa Inc"]),
    "JNJ": ("Johnson & Johnson", ["J&J", "Johnson and Johnson"]),
    "WMT": ("Walmart", ["Wal-Mart"]),
    "XOM": ("ExxonMobil", ["Exxon", "Mobil"]),
    "UNH": ("UnitedHealth", ["United Health Group", "UnitedHealthcare"]),
    "LLY": ("Eli Lilly", ["Lilly"]),
    "MA": ("Mastercard", ["MasterCard"]),
    "HD": ("Home Depot", ["The Home Depot"]),
    "CVX": ("Chevron", ["Chevron Corp"]),
    "MRK": ("Merck", ["Merck & Co"]),
    "ABBV": ("AbbVie", ["AbbVie Inc"]),
    "KO": ("Coca-Cola", ["Coke", "Coca Cola"]),
    "PEP": ("PepsiCo", ["Pepsi"]),
    "AVGO": ("Broadcom", ["Broadcom Inc"]),
    "COST": ("Costco", ["Costco Wholesale"]),
    "PFE": ("Pfizer", ["Pfizer Inc"]),
    "TMO": ("Thermo Fisher", ["Thermo Fisher Scientific"]),
    "MCD": ("McDonald's", ["McDonalds", "McDonald"]),
    "ACN": ("Accenture", []),
    "NKE": ("Nike", ["Nike Inc"]),
    "ORCL": ("Oracle", ["Oracle Corp"]),
    "CRM": ("Salesforce", ["Salesforce.com"]),
    "BAC": ("Bank of America", ["BofA"]),
    "ADBE": ("Adobe", ["Adobe Inc", "Adobe Systems"]),
    "CSCO": ("Cisco", ["Cisco Systems"]),
    "AMD": ("AMD", ["Advanced Micro Devices"]),
    "INTC": ("Intel", ["Intel Corp"]),
    "QCOM": ("Qualcomm", []),
    "IBM": ("IBM", ["International Business Machines"]),
    "GE": ("GE", ["General Electric"]),
    "BA": ("Boeing", ["Boeing Co"]),
    "CAT": ("Caterpillar", []),
    "GS": ("Goldman Sachs", ["Goldman"]),
    "MS": ("Morgan Stanley", []),
    "WFC": ("Wells Fargo", []),
    "C": ("Citigroup", ["Citi", "Citibank"]),
    "AXP": ("American Express", ["AmEx", "Amex"]),
    "BLK": ("BlackRock", []),
    "SPGI": ("S&P Global", ["S&P"]),
    "DE": ("John Deere", ["Deere"]),
    "RTX": ("Raytheon", ["RTX Corp", "Raytheon Technologies"]),
    "LMT": ("Lockheed Martin", ["Lockheed"]),
    "NOC": ("Northrop Grumman", ["Northrop"]),
    "GD": ("General Dynamics", []),
    "HII": ("Huntington Ingalls", []),
    "PLTR": ("Palantir", ["Palantir Technologies"]),
    "DELL": ("Dell", ["Dell Technologies"]),
    "HPE": ("HP", ["Hewlett Packard", "Hewlett-Packard", "HP Inc"]),
    "HPQ": ("HP Inc", ["Hewlett Packard"]),
    "T": ("AT&T", []),
    "VZ": ("Verizon", []),
    "TMUS": ("T-Mobile", ["T Mobile"]),
    "DIS": ("Disney", ["Walt Disney"]),
    "NFLX": ("Netflix", []),
    "SPOT": ("Spotify", []),
    "UBER": ("Uber", []),
    "LYFT": ("Lyft", []),
    "ABNB": ("Airbnb", []),
    "SNAP": ("Snap", ["Snapchat"]),
    "TWTR": ("Twitter", ["X Corp"]),
    "COIN": ("Coinbase", []),
    "HOOD": ("Robinhood", []),
    "SQ": ("Block", ["Square", "Square Inc"]),
    "PYPL": ("PayPal", []),
    "SHOP": ("Shopify", []),
    "ROKU": ("Roku", []),
    "ZM": ("Zoom", ["Zoom Video"]),
    "DOCU": ("DocuSign", []),
    "SNOW": ("Snowflake", []),
    "PATH": ("UiPath", []),
    "RBLX": ("Roblox", []),
    "U": ("Unity", ["Unity Technologies"]),
    "RIVN": ("Rivian", []),
    "LCID": ("Lucid", ["Lucid Motors"]),
    "F": ("Ford", ["Ford Motor"]),
    "GM": ("General Motors", []),
    "STLA": ("Stellantis", []),
    "TM": ("Toyota", ["Toyota Motor"]),
    "HMC": ("Honda", ["Honda Motor"]),
    "NIO": ("NIO", []),
    "X": ("U.S. Steel", ["US Steel", "United States Steel"]),
    "CLF": ("Cleveland-Cliffs", ["Cleveland Cliffs"]),
    "NUE": ("Nucor", []),
    "AA": ("Alcoa", []),
    "FCX": ("Freeport-McMoRan", ["Freeport McMoRan", "Freeport"]),
    "NEM": ("Newmont", ["Newmont Mining"]),
    "GOLD": ("Barrick Gold", ["Barrick"]),
    "SLB": ("Schlumberger", ["SLB"]),
    "HAL": ("Halliburton", []),
    "COP": ("ConocoPhillips", ["Conoco"]),
    "OXY": ("Occidental Petroleum", ["Occidental"]),
    "MPC": ("Marathon Petroleum", ["Marathon"]),
    "VLO": ("Valero", ["Valero Energy"]),
    "PSX": ("Phillips 66", []),
    "DJT": ("Trump Media", ["Truth Social", "Trump Media & Technology"]),
    "MSTR": ("MicroStrategy", []),
    "SMCI": ("Super Micro", ["Supermicro", "Super Micro Computer"]),
    "ARM": ("ARM Holdings", ["Arm"]),
    "AMAT": ("Applied Materials", []),
    "LRCX": ("Lam Research", []),
    "KLAC": ("KLA Corp", ["KLA"]),
    "MRVL": ("Marvell Technology", ["Marvell"]),
    "MU": ("Micron", ["Micron Technology"]),
    "WDC": ("Western Digital", []),
    "STX": ("Seagate", ["Seagate Technology"]),
    "NET": ("Cloudflare", []),
    "ZS": ("Zscaler", []),
    "CRWD": ("CrowdStrike", []),
    "S": ("SentinelOne", []),
    "PANW": ("Palo Alto Networks", ["Palo Alto"]),
    "FTNT": ("Fortinet", []),
    "DDOG": ("Datadog", []),
    "MDB": ("MongoDB", []),
    "ESTC": ("Elastic", []),
    "AI": ("C3.ai", ["C3 AI"]),
    "SOUN": ("SoundHound", []),
    "BBAI": ("BigBear.ai", []),
    "APLD": ("Applied Digital", []),
    "IREN": ("Iris Energy", []),
    "CORZ": ("Core Scientific", []),
    "MARA": ("Marathon Digital", ["Marathon Digital Holdings"]),
    "HUT": ("Hut 8", []),
    "RIOT": ("Riot Platforms", ["Riot Blockchain"]),
}

def build_lookup():
    """Returns a dict mapping lowercase name/alias/ticker -> ticker."""
    lookup = {}
    for ticker, (name, aliases) in COMPANIES.items():
        lookup[ticker.lower()] = ticker
        lookup[name.lower()] = ticker
        for alias in aliases:
            lookup[alias.lower()] = ticker
    return lookup

LOOKUP = build_lookup()
